config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

   if @person.save
     redirect_to people_path
   else
     render :new
   end
    # this doesn't render a view
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    # this doesn't render a view
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    # if @person.destroy
     redirect_to people_path
    # end
    # this doesn't render a view
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/peoples_helper.rb
module PeoplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>People</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

app/views/people/index.html.erb
<h1> People </h1>

<% @people.each do |person| %>
  <h2><%= person.name %></h2>
  <%= link_to 'Show person', person_path(person) %>
  

  <%= link_to 'Delete person', person, method: :delete %>

<% end %>
<br />
<br />
<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>Add New Person</h1>
<p>Find me in app/views/peoples/new.html.erb</p>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<h4><%= @person.age %></h1>
<h4><%= @person.hair_color %></h4>
<h4><%= @person.eye_color %></h4>